name: Update Assets
on:
  push:
    branch: [master]

jobs:
  deploy:
    name: Update Assets
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Upload plugins assets
      uses: 10up/action-wordpress-plugin-asset-update@stable
      env:
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
        SLUG: 5-anker-connect
        IGNORE_OTHER_FILES: true
        README_NAME: README.txt
